name: vertex_day_2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  
  # Storage & Database
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.0
  path: ^1.9.0
  sqflite: ^2.3.0
  shared_preferences: ^2.5.4

  # Connectivity & Network
  connectivity_plus: ^6.0.0
  http: ^1.2.0

  # Features
  local_auth: ^2.1.6
  mobile_scanner: ^3.0.0
  intl: ^0.20.2
  
  # UI & Fonts
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  drift_dev: ^2.16.0
  build_runner: ^2.4.8
  
  # Lints
  flutter_lints: ^6.0.0

  # Splash Screen Generator
  flutter_native_splash: ^2.4.0

  # App Icon Generator (NEW)
  flutter_launcher_icons: ^0.13.1

# Flutter Configuration
flutter:
  uses-material-design: true
  assets:
    - lib/assets/

# --- SPLASH SCREEN CONFIGURATION ---
flutter_native_splash:
  color: "#FFFFFF"
  image: lib/assets/vertex_logo-removebg-preview.png
  android_12:
    image: lib/assets/vertex_logo-removebg-preview.png
    color: "#FFFFFF"

# --- APP ICON CONFIGURATION (NEW) ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/app_logo.png"
  min_sdk_android: 21 # Needed for newer Android versions